// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaeUHhswBh-8s-MgVsneQcylxXsnW0f84',
    appId: '1:625200669376:android:ca6f2f4c1759b211214325',
    messagingSenderId: '625200669376',
    projectId: 'dissprojectdb',
    storageBucket: 'dissprojectdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJGMRrbQ0s0mbHTik1OmJRBQ_5Aao1GGk',
    appId: '1:625200669376:ios:ec208186cdd274a4214325',
    messagingSenderId: '625200669376',
    projectId: 'dissprojectdb',
    storageBucket: 'dissprojectdb.appspot.com',
    iosBundleId: 'jaydentest.moodtracker.2024',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByd2boZsamtvZ_Ql3ik2LKxa0WvQZqa5o',
    appId: '1:625200669376:web:77453dbaac4a6449214325',
    messagingSenderId: '625200669376',
    projectId: 'dissprojectdb',
    authDomain: 'dissprojectdb.firebaseapp.com',
    storageBucket: 'dissprojectdb.appspot.com',
    measurementId: 'G-ND7HYS2N02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJGMRrbQ0s0mbHTik1OmJRBQ_5Aao1GGk',
    appId: '1:625200669376:ios:0ba95eb2ffdbafbb214325',
    messagingSenderId: '625200669376',
    projectId: 'dissprojectdb',
    storageBucket: 'dissprojectdb.appspot.com',
    iosBundleId: 'com.example.moodtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByd2boZsamtvZ_Ql3ik2LKxa0WvQZqa5o',
    appId: '1:625200669376:web:19c94e17e9f95c81214325',
    messagingSenderId: '625200669376',
    projectId: 'dissprojectdb',
    authDomain: 'dissprojectdb.firebaseapp.com',
    storageBucket: 'dissprojectdb.appspot.com',
    measurementId: 'G-CF9TXQMRSK',
  );

}